add accordion solution
js-tasks-ru/htmlcss-20220414_lena4ertik pull request #5
Opened 2022-05-02 11:36 UTC by Chedakak

2022-05-02 11:37 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-03 07:33 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-03 13:15 UTC, Chedakak commented
Не поняла как изменить и переместить стрелочку влево свернуть/развернуть аккордион

2022-05-03 13:35 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-04 19:16 UTC, GSemikozov requested changes

2022-05-04 19:16 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion:first-child {
марджины на уровне блока не задаем, удалить

2022-05-04 19:16 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin-top: 8px;
этот отступ лучше задавать всем кроме первого, можно так: `.accordion__item:not(:first-child) { margin-top: 8px; }`

2022-05-04 19:16 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding-left: 32px;
паддинги нужны со всех сторон, не только сверху и слева

2022-05-04 19:16 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    width: 649.31px;
ширину и высоту здесь не нужно задавать

2022-05-04 19:16 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +            <div class="accordion-open">
это какой-то лишний элемент)

2022-05-04 19:16 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +                    <details open>
именно на этом теге должен быть класс accordion__item (+ избавимся от лишней вложенности)

2022-05-04 19:16 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +                        <summary>
а здесь - accordion__title

2022-05-05 09:19 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-05 10:16 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-05 16:54 UTC, GSemikozov approved these changes

2022-05-05 16:54 UTC, merged